// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
)

type LiteFSEntry struct {
	ID       string         `json:"id"`
	ParentID sql.NullString `json:"parentID"`
	Name     string         `json:"name"`
	Modtime  string         `json:"modtime"`
	Content  []byte         `json:"content"`
}

type SchemaMigration struct {
	Version string `json:"version"`
}
